services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react-frontend-production
    ports:
      - "80:80"
    volumes:
      - ./nginx-config-production/conf.d:/etc/nginx/conf.d/:ro
      - ./nginx-config-production/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./laravel-app/storage/blog/images:/var/www/public/images:ro
    networks:
      - app-network  

  app:
    build:
      context: .
      dockerfile: Dockerfile.laravel-backend-production
    container_name: laravel-backend
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - .env.production
    volumes:
      - ./laravel-app:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge      