services:
  nginx:
    image: nginx:latest
    container_name: nginx-webserver
    ports:
      - "80:80"
    volumes:
      - ./nginx-config/conf.d:/etc/nginx/conf.d/:ro #directory of default.conf
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro  # Bind only nginx.conf FILE!
      - ./laravel-app/storage/blog/images:/var/www/public/images:ro # Bind the blog images directory for more efficient image sharing
  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile.react-frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./react-frontend:/react-frontend
  app:
    build:
      context: .
      dockerfile: Dockerfile.laravel-backend
    container_name: laravel-backend
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - .env
    volumes:
      - ./laravel-app:/var/www # the blog folder is already included inside the storage folder
      #- ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
